export enum SaleOrderStatusType {
  CREATED = 'CREATED',
  SENDING = 'SENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
  DISAPPROVED = 'DISAPPROVED',
  FINISHED = 'FINISHED',
  CANCELED = 'CANCELED',
}

export enum PurchaseOrderStatusType {
  CREATED = 'CREATED',
  SENDING = 'SENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
  DISAPPROVED = 'DISAPPROVED',
  FINISHED = 'FINISHED',
  CANCELED = 'CANCELED',
}

export enum OrderPaymentStatusType {
  PENDING = 'PENDING',
  PAID = 'PAID',
  CANCELED = 'CANCELED',
}
